/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppIcon: typeof import('./src/components/AppIcon.vue')['default']
    BottomNavBar: typeof import('./src/components/BottomNavBar.vue')['default']
    LoadingState: typeof import('./src/components/LoadingState.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanEmpty: typeof import('vant/es')['Empty']
    VanOverlay: typeof import('vant/es')['Overlay']
  }
}
